title: "Electronic Engineering + Mechatronics"
description: "Electronic Engineering and Mechatronics at UTEC"

url: "https://L30nardoSV.github.io"
baseurl: "/elmt-utec"

markdown: kramdown

collections:
  research:
    output: true

  people:
    output: true

  laboratories:
    output: true

  opportunities:
    output: true
